fixed typo
MickaelRigault/simsurvey pull request #43
Opened 2020-07-08 11:57 UTC by asaguescar

It seems to work fine once the typo is fixed.

2020-07-10 14:41 UTC, asaguescar commented on simsurvey/utils/random.py
> +    if type(skymap)!=tuple:
This makes sense, I chose that because of the skymap format for both cases. But I understand that we want to keep the same format, and the user have to make sure that the input is a dict.

2020-07-10 14:46 UTC, ufeindt commented on simsurvey/simultarget.py
> +            if not self.simul_parameters["zcmb"]:
Alternative idea: maybe we can isolate everything ra, dec related into a 2d skymap function (maybe call that one skymap) and then make a skymap_3d function that also takes distmod and distprop as argument and calls the 2d function and then generates the redshifts in addition. That way users could just get ra, dec for a 2d skymap if they want to.

2020-07-10 14:54 UTC, asaguescar commented on simsurvey/simultarget.py
> +            if not self.simul_parameters["zcmb"]:
Sounds good. Then we want to have different argumetns in the Transient generator? say 2D or 3D skymap?

2020-07-10 14:59 UTC, ufeindt commented on simsurvey/simultarget.py
> +            if not self.simul_parameters["zcmb"]:
I think we should also restructure _update_simulation_() a little bit to avoid doing the same thing twice. (Right now it generates ra, dec and z only to replace them if there is a skymap. It would be better to only generate them in the cases when we need to.

So something like this:
```python
if self.event_coverage["skymap"] is not None and all([key in self.event_coverage["skymap"].keys() for key in ("distmu", "distsigma"):
    # Raise an error if ntransient not set
    # Run 3d skymap generator
else:
    # Generate z from rate (potentially fixing number to input ntransient)
    if self.event_coverage["skymap"] is not None:
        # Run 2d skymap generator
    else:
        # Generate RA, Dec from uniform distribution
```

2020-07-10 15:17 UTC, ufeindt commented on simsurvey/simultarget.py
> +            if not self.simul_parameters["zcmb"]:
> Sounds good. Then we want to have different argumetns in the Transient generator? say 2D or 3D skymap?

Sorry, missed your response. I think we could just handle it by checking for the distmu and distsigma keywords, see my proevious comment. Then, of course, we need to also clarify this behavior in the docstring.

2020-07-10 15:51 UTC, asaguescar commented
@ufeindt  I have resolved the comment. Could you have a look at it?  Thanks!!

2020-07-11 07:11 UTC, ufeindt requested changes

2020-07-11 07:11 UTC, ufeindt commented on simsurvey/utils/random.py
> +def radec_skymap(npoints=1,skymap={},ra_range=None,dec_range=None,
I'd like to make the arguments more explicit, so maybe drop the default value for npoints and replace skymap with `prob`. If you can add a docstring similar to the ones in simultraget that would be great but I can do that later, too.

2020-07-11 07:11 UTC, ufeindt commented on simsurvey/utils/random.py
>  def radecz_skymap(npoints=1,skymap={},ra_range=None,dec_range=None,
In the same vein as the comment above, maybe we can make the argument more explicit and unpack the skymap dictionary in `simultarget.py`. I'd suggest splitting `skymap` into `prob`, `distmu`, and `distsigma` and making them required arguments.

2020-07-11 07:11 UTC, ufeindt commented on simsurvey/utils/random.py
>      prob[prob < 0.] = 0.
A lot of this code is duplicated here (basically everything until and including line 116). The generation of `ipix` could be moved into a separate function (maybe called `skymap_generate_ipix`) that is called by both skymap functions.

2022-07-29 16:46 UTC, closed without merging